### ISSUE TITLE
棋盘格在相机坐标系下的位姿如何求？

### ISSUE THREAD

**Issue by allen333hot** [DannyChen1994/hand-eye-calibration#2]
path1中DATA包括拍摄的棋盘格图片和棋盘格在相机坐标系下的位姿信息.txt，这个.txt如何得到的？
感谢！

**Comment by DannyChen1994** [comment]
是通过`zed-eye2hand.py`中的函数识别棋盘格角点得到的，需要根据棋盘格的网格边长和数量修正参数，以及相机的数据源。

**Comment by allen333hot** [comment]
非常感谢您的回复！棋盘格在相机坐标系下的位姿已经求得。
新的问题是：1、读取路径文件（求得的txt）报错。
![image](https://github.com/DannyChen1994/hand-eye-calibration/assets/133631228/b5e866cb-8f69-4e8c-826e-0b08b27c263d)
2、手动输入chess_to_cam以及end_to_base列表数据后，验证显示不太准确，可能是哪些问题，或者哪些方面可以改进。
![image](https://github.com/DannyChen1994/hand-eye-calibration/assets/133631228/27b56a30-1171-447e-94d9-6cd56b78f533)
期待您抽空赐教。

**Comment by DannyChen1994** [comment]
读取路径文件（求得的txt）报错是“\”和“/”的问题吧。计算不准可能是给出的数值不对问题？尝试增加数量`numData=3`

**Comment by allen333hot** [comment]
> 读取路径文件（求得的txt）报错是“\”和“/”的问题吧。计算不准可能是给出的数值不对问题？尝试增加数量`numData=3`

windows下，改用了“/”还是报错。dis差的有点多了，实际大概110cm左右。感谢您的回复和建议
![image](https://github.com/DannyChen1994/hand-eye-calibration/assets/133631228/3e6a1b58-534c-4984-88e0-02cf0f673d85)

**Comment by allen333hot** [comment]
> > 读取路径文件（求得的txt）报错是“\”和“/”的问题吧。计算不准可能是给出的数值不对问题？尝试增加数量`numData=3`
> 
> windows下，改用了“/”还是报错。dis差的有点多了，实际大概110cm左右。感谢您的回复和建议 ![image](https://user-images.githubusercontent.com/133631228/273851265-3e6a1b58-534c-4984-88e0-02cf0f673d85.png)

![image](https://github.com/DannyChen1994/hand-eye-calibration/assets/133631228/3b8750c1-a8b9-40cb-b2ea-8dfc171756a0)

**Comment by LZzzin1** [comment]
您好，请问dist过大是如何解决的呢

**Comment by allen333hot** [comment]
> 您好，请问dist过大是如何解决的呢

您使用的是什么相机呢？确保相机内参正确，光线、标定板等都是影响因素

**Comment by allen333hot** [comment]
> 您好，请问dist过大是如何解决的呢

多拍几组，然后，我换了玻璃基的标定板，结果就好一些了

**Comment by LZzzin1** [comment]
感谢回复，我使用的是纸打印的标定板，我认为objp的值的设定有一定问题，将其乘以25mm是不对的，因为单位是cm，应该为2.5，但改为2.5后结果还有一定的误差，我正在尝试更改误差

**Comment by allen333hot** [comment]
> 感谢回复，我使用的是纸打印的标定板，我认为objp的值的设定有一定问题，将其乘以25mm是不对的，因为单位是cm，应该为2.5，但改为2.5后结果还有一定的误差，我正在尝试更改误差

做的怎么样了呢，手眼标定
